name: Discord Push Notification

on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord notification
        run: |
          curl -H "Content-Type: application/json" \
          -d "{
            \"content\": \"🚀 Nouveau push
Repo : ${{ github.repository }}
Auteur : ${{ github.actor }}
Commit : ${{ github.event.head_commit.message }}
Fichier modifié : ${{ github.event.head_commit.modified[0] }}\"
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}